### PR TITLE
Support for Object type numpy arrays

### PR DESCRIPTION
**Pull request by Chris-george-anil**
Added support,  weights that  are passed as Numpy arrays with dtype as objects

### CODE REVIEW

**Comment by danieljanes** [comment]
Thanks for the PR @Chris-george-anil !

Could you elaborate on what the effects of this change will be? I'm not that familiar with the `allow_pickle` argument, so it's difficult to understand the impact of this change. What kind of use cases does it enable? Is it incompatible with any prior behavior?

**Comment by tanertopal** [comment]
@Chris-george-anil Any update or thoughts form your side?

**Comment by Chris-george-anil** [comment]
> @Chris-george-anil Any update or thoughts form your side?

Nothing else @tanertopal , it works fine on my device.

**Comment by mariaboerner1987** [comment]
@tanertopal and @Chris-george-anil 
how do we gonna proceed with this PR?

**Comment by tanertopal** [comment]
@Chris-george-anil thank you for your effort and this PR! All contributions are highly appreciated. Out of security considerations we are not going to merge this as it would allow clients the execution of arbitrary code on the server. Further this would mean each client can likewise execute any code on any other client using the captured server as a proxy. We are looking forward to your future work in with Flower :)

**Pull request closed without merging**
