### PR TITLE
Implement FedMedian

### LINKED ISSUE #1405: Implement Krum, MultiKrum and FedMedian
### Describe the type of feature and its functionality.

I am working on Federated Learning in adversarial settings, where clients can perform model poisoning in order to degrade the aggregated model performances. To mitigate the effect of model poisoning attacks I have implemented Krum, MultiKrum and FedMedian as strategies. 

Would you be interested to include them in the main repository?

### Describe step by step what files and adjustments are you planning to include.

I am planning to create three new files in the strategy directory: krum.py, multikrum.py and fedmedian.py.

### Is there something else you want to add?

Krum and MultiKrum are described [here](https://proceedings.neurips.cc/paper/2017/file/f4b9ec30ad9f68f89b29639786cb62ef-Paper.pdf).

### PR DESCRIPTION
**Pull request by edogab33**
#### Reference Issues/PRs

Fixes #1405.

#### What does this implement/fix? Explain your changes.

Implemented the aggragation function FedMedian.

#### Any other comments?

Let me know if everythink is ok so that I can also implement other aggregation functions. Should I also update the CODEOWNERS file?

### CODE REVIEW

**Comment by danieljanes** [comment]
Thanks for the PR @edogab33 !

General code structure looks good. CI is failing because of wrongly sorted imports: https://github.com/adap/flower/actions/runs/3282834654/jobs/5406769736

The easiest way to fix this is to run `./dev/format.sh`

**Comment by danieljanes** [comment]
@edogab33 let me know if we can help with making the CI checks pass. There are still a few linter warning, but they should be easy to resolve.

**Comment by edogab33** [comment]
> @edogab33 let me know if we can help with making the CI checks pass. There are still a few linter warning, but they should be easy to resolve.

I was looking for a way to run GitHub actions locally without using Docker in order to not spam useless commits in your repository but then I had to come back to my original work so I put that on hold :D 

I'll try to solve the issue ASAP without running the tests locally, I apologize in advance for the number of small commits.

**Comment by danieljanes** [comment]
Thanks for being so considerate @edogab33, appreciated :) Don't worry about many small commits, we always squash commits when the PR gets merged, so it'll look like one clean commit on `main`.

If we can manage to merge this PR before the end of the week, it will make it into the Flower 1.1 release.

**Comment by edogab33** [comment]
It seems like the test doesn't like `np.median()` at all. 

@danieljanes Any idea on how to solve this?

**Comment by danieljanes** [comment]
@edogab33 that's surprising, `np.median` should have type annotations as of NumPy 1.22: https://github.com/numpy/numpy/pull/20034

Feel free to add a `# type: ignore` at the end of the line that calls `np.median`, we'll take care of this after increasing the minimum NumPy version to 1.22.

**Comment by edogab33** [comment]
@danieljanes yes, that's odd. However I implemented the workaround, now it's ready to be merged.

As soon as possible I'll start to include all the other strategies I've implemented so far :)

**Comment by danieljanes** [comment]
@edogab33 awesome, I look forward to these other strategies!

& great, PR is green 🎉 I'm just waiting on feedback from one other reviewer. If you still up for it you could add a section to the release notes (in the `Unreleased` section): https://github.com/adap/flower/blob/main/doc/source/changelog.md (ideally a short bold headline + PR ref followed by a description of one or more sentences)

**Comment by pedropgusmao** [comment]
This PR looks good. I'm just not sure about the number of tests. Apparently, it would just need the last one. @danieljanes , do we have any policy on these?

**Comment by danieljanes** [comment]
@pedropgusmao no policy yet, I'd suggest we merge and then update if our approach to testing changes

**Review by danieljanes — APPROVED** [review]

**Comment by edogab33** [comment]
> @edogab33 awesome, I look forward to these other strategies!
> 
> & great, PR is green 🎉 I'm just waiting on feedback from one other reviewer. If you still up for it you could add a section to the release notes (in the `Unreleased` section): https://github.com/adap/flower/blob/main/doc/source/changelog.md (ideally a short bold headline + PR ref followed by a description of one or more sentences)

I did not have the time to update the changelog before the merging. Should I open a new PR for it?

**Comment by danieljanes** [comment]
@edogab33 all good, thanks for checking!

**Pull request merged**
