### PR TITLE
Add FedPFT baseline

### PR DESCRIPTION
**Pull request by mahdibeit**
### Description
This PR adds FedPFT baseline as introduced in the "Parametric Feature Transfer: One-shot Federated Learning with Foundation Models" paper.

### Related issues/PRs
Implements #3232

### Explanation
Implements FedPFT as a baseline.

### Checklist

- [x] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.ai/docs/writing-documentation.html)
- [ ] Update the changelog entry below
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.ai/join-slack/) (channel `#contributions`)

### Any other comments?

<baselines>

### CODE REVIEW

**Comment by jafermarq** [comment]
Hi @mahdibeit , i did a couple of small fixes. now the test pipeline starts but you'll notice that `mypy` shows some errors. Let me know when you have some time to take a look.

**Comment by mahdibeit** [comment]
Hi @jafermarq, thanks for taking the time to fix the issues. I noticed that the test-baseline.sh script that I ran did not do all the tests (like mypy or lint). I fixed all the issues this time and ran it successfully without errors. Let me know if it requires any further changes.

**Comment by jafermarq** [comment]
@mahdibeit , cool. The tests pass. I'll take a closer look into the code today/tomorrow and get back to you if i see something that we could improve. In most baselines, contributors decided to add their contact details (e.g. email address) in the `contributors` point under the `About this baseline` section. Feel free to do that if you wish.

**Comment by mahdibeit** [comment]
Awesome. Thank you so much @jafermarq. I look forward to your review. Thanks for your suggestion. I added my email to the README file.

**Review by jafermarq — COMMENTED** [review]
Hi @mahdibeit  , I was able to reproduce the results you show in the plot at the end of your `README.md` (but needed to make the small changes i suggest in my review below). Let me know what you think.

The PR is in a pretty good state so once those small issues are resolved it can be merged 🙌

**Comment by mahdibeit** [comment]
Hi @jafermarq, that is great news. I merged the suggested changes. Everything looks great to me.

**Review by jafermarq — APPROVED** [review]
Great! `FedPFT` is great and really fast! 🚀

**Pull request merged**
