### PR TITLE
Add original data download link and pre-process code for FedBN

### PR DESCRIPTION
**Pull request by MeiruiJiang**
- Update readme with download link
- Add data preprocess file in utils

### CODE REVIEW

**Comment by jafermarq** [comment]
Thank you for adding this. Certainly the `data_preprocessing.py` seems needed to run the FedBN example. Could you add maybe a simple script that downloads and extracts MNIST and SVHN into the `data/` directory (maybe even creates it). Then the user can simply download the other three datasets following the GDrive links. 

also probably you want to update the `project.toml` to include the dependencies added in your `data_preprocessing.py` (It seems Matplotlib is not needed)

**Comment by jafermarq** [comment]
Also, it might be useful if in addition to the `data_preprocessing.py` script we could have a "data_download" script that downloads all the original MNIST, MNIST_M, SVHN, SynthDigits and USPS datasets. Then, `data_preprocessing.py` could be expanded to also create the partitions for each dataset. This would make the FedBN baseline code in Flower fully self-contained.

**Comment by MeiruiJiang** [comment]
> Also, it might be useful if in addition to the `data_preprocessing.py` script we could have a "data_download" script that downloads all the original MNIST, MNIST_M, SVHN, SynthDigits and USPS datasets. Then, `data_preprocessing.py` could be expanded to also create the partitions for each dataset. This would make the FedBN baseline code in Flower fully self-contained.

Hi Javier,
Many thanks for  your suggestions, I have updated and made a new commit including the data download script, please check~

**Comment by MeiruiJiang** [comment]
> Thank you for adding this. Adding the `data_preprocessing.py` script would require you to update the `project.toml` to include the dependencies added (`sklearn` and `scipy`) in your `data_preprocessing.py` (It seems Matplotlib is not needed).

I am not familiar with the toml regulations, would you mind giving some guides on how to include the right dependencies? I am not sure how to insert and which version should be used.

**Comment by mariaboerner1987** [comment]
> > Thank you for adding this. Adding the `data_preprocessing.py` script would require you to update the `project.toml` to include the dependencies added (`sklearn` and `scipy`) in your `data_preprocessing.py` (It seems Matplotlib is not needed).
> 
> I am not familiar with the toml regulations, would you mind giving some guides on how to include the right dependencies? I am not sure how to insert and which version should be used.

Hi @MeiruiJiang ,
thank you for your contribution. I will have a look and also modify the` pyproject.toml` file. 
FYI @jafermarq (and also thanks for having a first look into it)

**Comment by mariaboerner1987** [comment]
@danieljanes can you please merge this PR to my baseline branch

**Pull request merged**
