### PR TITLE
new contributor

### PR DESCRIPTION
**Pull request by piyushgit011**

### CODE REVIEW

**Comment by tanertopal** [comment]
@piyushgit011 Thank you for the PR! Can you elaborate a bit on the description and adjust the title meaningfully so it relates to the change you are proposing?

**Comment by piyushgit011** [comment]
i have changed documentation and code for new contributers. As advised in the contributors section which is to start contribution.
so new contributors can contribute their first pr.

**Comment by danieljanes** [comment]
Hi @piyushgit011 , great to see that you want to contribute!

This change would revert an earlier PR (#1494), so we won't merge it as-is. One opportunity would be to change a different title in a similar way, for example, `Implementing Strategies` -> `Implement Strategies`. You could either revert the changes in this PR and then add the new changes, or we close this PR, and you open a new one. Up to you :)

**Comment by piyushgit011** [comment]
okay i am closing this and i will add new pr

**Pull request closed without merging**
