### PR TITLE
Fix build of docker base image

### PR DESCRIPTION
**Pull request by Robert-Steiner**
## Issue

The values (python versions) in the matrix were interpreted as floats. When the value `3.10` was passed to the build argument `PYTHON_VERSION` the zero was cut off. This lead the docker build command to fail because it tried to install python `3.1`. 

### Description

- convert python version to strings
- turned the value for `fail-fast` to `false`. if one build fails, we still can push the other.
- make artifact name unique (hash of the build args) to prevent jobs from overwriting each other's artifacts

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.dev/docs/writing-documentation.html)
- [ ] Update [changelog](https://github.com/adap/flower/blob/main/doc/source/changelog.rst)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### CODE REVIEW

**Comment by tanertopal** [comment]
My bad. I should have caught this in the review. We had that issue in the past, and I had forgotten it.

**Comment by Robert-Steiner** [comment]
> My bad. I should have caught this in the review. We had that issue in the past, and I had forgotten it.

Don't worry, I should have tested it to make sure it works

**Comment by Robert-Steiner** [comment]
ci passed this time: https://github.com/adap/flower/actions/runs/7169819131

**Comment by Robert-Steiner** [comment]
there was another small error that i had fix. [if job upload an artifact with the same name, they will override each other.](https://github.com/actions/upload-artifact)

**Review by tanertopal — APPROVED** [review]

**Pull request merged**
