### PR TITLE
Create FedBN Baseline Example

### PR DESCRIPTION
**Pull request by mariaboerner1987**
- create 5 clients
-  create 1 server
- create model architecture as described in the paper for benchmark experiments
- create a run.sh to start easily 5 clients in parallel

### CODE REVIEW

**Comment by MeiruiJiang** [comment]
Dear Maria,

Many thanks for your great work! I have check the updates, all the code look clean and clear. 
Please feel free to let me know if can help. 

Best,
Meirui

**Comment by jafermarq** [comment]
I think the the `Dataset Download` part of the readme needs to be clearer. It seems that only the `Benchmark(Digits)`  --[link](https://drive.google.com/file/d/1moBE_ASD5vIOaU8ZHm_Nsj0KAfX5T0Sf/view?usp=sharing) -- dataset is what is needed to be downloaded from the FedBN repo. Then, the content of that zip file has to go in `data/`. Else, the unzip file can be just renamed "data".

**Review by rfdickerson — DISMISSED** [review]
Looks really good! Was looking for a FedBL implementation.

**Comment by mariaboerner1987** [comment]
@danieljanes pytest is now included (thanks to @pedropgusmao )

**Review by danieljanes — DISMISSED** [review]

**Review by danieljanes — DISMISSED** [review]

**Review by danieljanes — DISMISSED** [review]

**Review by danieljanes — APPROVED** [review]

**Pull request merged**
