### PR TITLE
Implement Bulyan

### PR DESCRIPTION
**Pull request by edogab33**
Implements #1612

### CODE REVIEW

**Comment by danieljanes** [comment]
@edogab33 is this still WIP? Would be great to convert this PR to a draft, remove WIP from the title, and mark as ready once we can start to review

**Comment by BaselOmari** [comment]
Hey Edoardo, I'd like to take over and contribute to this as well.

**Comment by edogab33** [comment]
> Hey Edoardo, I'd like to take over and contribute to this as well.

Hi Basel, actually I've already implemented it. It's just a matter of integrating it into Flower... so let me push my code and see if you can contribute somehow

**Comment by danieljanes** [comment]
Thanks for pushing the implementation @edogab33. @BaselOmari, since you already looked into this topic, would you mind reviewing and testing the PR?

@edogab33, one nitpick: could you revert the change in `flwr_experimental`?

**Comment by adam-narozniak** [comment]
Hi @edogab33! I will merge your PR into a new branch, so I can make modifications to fix the tests before merging it into main. Thanks for your contribution! 🌼

**Pull request merged**
