### PR TITLE
Proto Linter | Add clang-format to Flower

### PR DESCRIPTION
**Pull request by CanTuerk**
This PR will add clang-format to `test.sh` and `format.sh` in the Flower repository. Refers to #583 .

### CODE REVIEW

**Review by danieljanes — APPROVED** [review]

**Review by danieljanes — CHANGES_REQUESTED** [review]
Looks good, we need to install clang-format on the CI though

**Review by danieljanes — APPROVED** [review]

**Review by tanertopal — APPROVED** [review]

**Comment by pedropgusmao** [comment]
clang-format needs to be installed on the user side as well. I'm getting `xargs: clang-format-10: No such file or directory` when trying to run `dev/format.sh`

**Comment by danieljanes** [comment]
Oh right, thanks for mentioning it. Should we add it to `bootstrap.sh`? Or should we run it optionally depending on whether the user has it installed or not?
@pedropgusmao @tanertopal

**Comment by pedropgusmao** [comment]
I would run it optionally, but if the CI job fails, then I guess the developer would not be able to fix it?

**Comment by danieljanes** [comment]
One other option would be to install it via pip: https://github.com/mgevaert/clang-format-wheel/

**Comment by pedropgusmao** [comment]
Yes, I think that's a better solution it is well maintained.

**Comment by danieljanes** [comment]
Follow-up issue #594

**Pull request merged**
