### PR TITLE
Flower Baselines: FedAvg CIFAR10

### PR DESCRIPTION
**Pull request by RashidDHera**
### Checklist

- [x] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.dev/docs/writing-documentation.html)
- [ ] Update [changelog](https://github.com/adap/flower/blob/main/doc/source/changelog.rst)
- [x] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### CODE REVIEW

**Comment by danieljanes** [comment]
Hi @RashidDHera , thanks for the PR! 

We'll start reviewing your PRs soon. How does this PR related to the previous one, could they be merged into one?

One note: Don't be surprised when you update this branch with the latest changes from `main` :) We changed the structure in `baselines` just yesterday, and the code that used to be in `baselines` is now in `baselines/flwr_baselines`. We will update the documentation shortly.

**Comment by RashidDHera** [comment]
Hello danieljanes , they are basically the same in terms of content. The problem was that ..dev/test.sh failed and produced errors with the yesterday's one during test_baselines. In this new one I checked and ensured the test.sh was running without errors on my machine.
Can you please first run... test baselines to see if there are  errors?
Thanks.

**Comment by jafermarq** [comment]
Hi @RashidDHera , thanks for putting the effort! can you move your `fedavg_cifar10` directory (i.e. the code you are contributing) into `baselines/flwr_baselines/publications`? (so it sits next to the other baselines?). You can commit that in your repo and branch `rashid_flwr` and the changes will be reflected here.

**Comment by charlesbvll** [comment]
Hi @RashidDHera, is it ok for you if we merge this PR in a new branch in order to work on it ourselves?

**Comment by RashidDHera** [comment]
It is OK. No problem.
Go ahead and merge it. 
please expedite the process, it has taken long.
Thanks

**Pull request merged**
