### PR TITLE
Documentation part 1 of DP in FL with Flower

### PR DESCRIPTION
**Pull request by ElnathanTiokou**
### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.dev/docs/writing-documentation.html)
- [ ] Update [changelog](https://github.com/adap/flower/blob/main/doc/source/changelog.rst)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### CODE REVIEW

**Comment by panh99** [comment]
Hi @ElnathanTiokou ! Thanks for your great work. The tutorial is well-written and well-organized. 
Just some minor concerns. First, I would suggest that the DP tutorial should focus on the DP topic and elaborate on how to use what's already there in Flower. Discussing Secure Aggregation (SA) and the combination of two techniques may might go beyond the intended scope. Besides, I believe that the GIF used to illustrate SA + DP in this tutorial originates from [Google Research](https://ai.googleblog.com/2023/03/distributed-differential-privacy-for.html). I don't think we can use that GIF for legal reasons.

**Comment by ElnathanTiokou** [comment]
Thank you for the feedback @panh99 I actually notified @danieljanes about the visuals, all of them need to be customized for Flower with our Color. 
Thank you I take note on elaborating on how to use what's already there in Flower. ( This is actually what I'm working on right now. The step by steps guide with the Flower DP functions. 
This first document was more of an explanatory file around the whole concept of DP in FL and a little bit beyond (An overview). Thank you for the remarks.

**Comment by panh99** [comment]
> 

Hi @ElnathanTiokou ! We would recommend avoiding discussing the combination of SA and DP within this tutorial. It would be better to separate the SA + DP thing into a different tutorial. Besides, just to clarify, you mean that the GIF from Google Research will be replaced by other usable images, right?

**Comment by ElnathanTiokou** [comment]
Well noted. I'll stick to DP. And yes the GIF was supposed to be replaced. But since SA shouldn't figure in, I'll just take it off.

**Pull request closed without merging**
