### PR TITLE
Implementation of fedbn on client side

### PR DESCRIPTION
**Pull request by MeiruiJiang**
Implementation of FedBN
change model with BN layers added
modified fuctions: get/set_prameters

### CODE REVIEW

**Comment by danieljanes** [comment]
@MeiruiJiang thanks for the PR, this looks great!
I'll run some regression tests and add a flag that enables users to enable/disable FedBN, then we can merge

**Comment by MeiruiJiang** [comment]
> @MeiruiJiang thanks for the PR, this looks great!
> I'll run some regression tests and add a flag that enables users to enable/disable FedBN, then we can merge

Great! Thanks and look forward to the Flower with FedBN.

**Review by danieljanes — APPROVED** [review]
Will add the flag to enable/disable FedBN in a follow-up PR.

**Comment by danieljanes** [comment]
Merged, thank again for the PR @MeiruiJiang!

**Pull request merged**
