### PR TITLE
refactor/Fix typos at comments and variable names in Python files

### PR DESCRIPTION
**Pull request by sisco0**
Some typos were found in the Python comments by using the next method:

1. Create `extractcomments.py` file with the next content:
```python3
#!/usr/bin/env python3
import argparse
import io
import tokenize


if __name__ == "__main__":
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('filename')
    args = parser.parse_args()

    with io.open(args.filename, "r", encoding="utf-8") as sourcefile:
        for t in tokenize.generate_tokens(sourcefile.readline):
            if t.type == tokenize.COMMENT: # We changed this line by using tokenize.NAME at a second run
                print(t.string.lstrip("#").strip())
```
2. Run the next bash script supposing you could access the repository root folder by using `../flower`:
```bash
for f in ../flower/src/py/**/*.py; do ./extractcomments.py $f >> ~/comments.txt; done
aspell <~/comments.txt --lang=en list | sort | uniq -c | sort -n > ~/typos.txt
```
3. Review `~/comments.txt` file and fix the corresponding issues manually by using `grep -iRn`, if the number of issues is high then use `sed -i`.

I attach the referred `typos.txt` output file.
<details> <summary>Click here to see typos.txt for comments</summary>

```text
      1 accross
      1 Adagrad
      1 CIFAR
      1 ClientManager
      1 corosponding
      1 cpu
      1 cv
      1 deserialize
      1 deserialized
      1 FastAndSlow
      1 flwr
      1 fontsize
      1 formatter
      1 GetParameters
      1 GetWeights
      1 GRPCBridge
      1 GrpcClientProxy
      1 hostname
      1 idx
      1 ImageNet
      1 InstanceId
      1 InstanceStatus
      1 Instanstiate
      1 JSON
      1 linecharts
      1 Lipschitz
      1 logfiles
      1 mapLogRecords
      1 Mem
      1 ndarrays
      1 noqa
      1 np
      1 NumPy
      1 NumPyClient
      1 permuations
      1 Pre
      1 Prepae
      1 PrivateIpAddress
      1 PublicIpAddress
      1 RayClientProxy
      1 reachability
      1 rnd
      1 RPCs
      1 Runtime
      1 setFormatter
      1 Simluate
      1 SSHPort
      1 StopIteration
      1 stutdown
      1 subdir
      1 tearDown
      1 toplevel
      1 Uncomment
      1 utf
      1 vCPU
      1 xticklabels
      1 xticks
      2 args
      2 cid
      2 datasets
      2 durations
      2 environ
      2 FedAvg
      2 FitIns
      2 FitRes
      2 FlowerServiceServicer
      2 GRPC
      2 init
      2 logfile
      2 logserver
      2 MNIST
      2 os
      2 positiv
      2 ProtoBuf
      2 ServerMessage
      2 Teardown
      2 unselected
      3 Deserialize
      3 FedFS
      3 http
      3 initializer
      3 Keras
      3 logdir
      4 docstring
      4 gRPC
      4 isinstance
      4 lr
      4 msg
      5 mypy
      5 proto
      6 unsubscriptable
     10 num
     20 dataset
     32 config
    125 pylint
    160 Adap
    160 GmbH
```
</details>

<details> <summary>Click here to see typos.txt for names</summary>

```text
      1 ABCMeta
      1 AdapterIntegrationTestCase
      1 AdapterTestCase
      1 APIClient
      1 assertGreater
      1 AssertionError
      1 baseurl
      1 basicConfig
      1 BlockDeviceMappings
      1 CategoricalAccuracy
      1 CenterCrop
      1 CifarTestCase
      1 ClusterIntegrationTestCase
      1 ConfigError
      1 ConfigParser
      1 CreateInstancesTestCase
      1 css
      1 DockerAdapterIntegrationTestCase
      1 DPModelInspector
      1 EnumDescriptor
      1 EnumTypeWrapper
      1 ExtraArgs
      1 FashionMnistPartitionedTestCase
      1 FastAndSlowTestCase
      1 favicon
      1 fedadam
      1 fedyogi
      1 FileDescriptor
      1 FileHandler
      1 finfo
      1 FlowerService
      1 FlowerServiceServicerTestCase
      1 fname
      1 frombuffer
      1 getcwd
      1 getvalue
      1 GlobalAveragePooling
      1 GradientTape
      1 GrpcClientProxyTestCase
      1 hasattr
      1 IamInstanceProfile
      1 ImageClassificationPartitionedTestCase
      1 ImageDataGenerator
      1 ImageId
      1 IncludeAllInstances
      1 InstanceInitiatedShutdownBehavior
      1 InstanceType
      1 isabs
      1 isclose
      1 isfile
      1 itertools
      1 kaiming
      1 KeyName
      1 LightningModule
      1 listdir
      1 LogserverTest
      1 LSTM
      1 mapLogRecord
      1 markersize
      1 MaxCount
      1 maxpool
      1 MaxPooling
      1 maxsize
      1 metaclass
      1 MethodDescriptor
      1 MinCount
      1 mul
      1 multinomial
      1 ncol
      1 NodeDef
      1 nonlinearity
      1 NotFound
      1 OpsSet
      1 preprocessing
      1 prog
      1 PropertiesEntry
      1 pyplot
      1 RandomHorizontalFlip
      1 RandomResizedCrop
      1 RegisterEnumDescriptor
      1 RegisterFileDescriptor
      1 RegisterServiceDescriptor
      1 rescale
      1 rfile
      1 rpcs
      1 savez
      1 SecurityGroupIds
      1 ServiceDescriptor
      1 shakespeare
      1 ShakespeareDataset
      1 simplefilter
      1 sint
      1 staticmethod
      1 StatusCode
      1 StreamHandler
      1 SubnetId
      1 subprocess
      1 TagSpecifications
      1 Tanh
      1 TestStringMethods
      1 TF
      1 UC
      1 uint
      1 urlretrieve
      1 UserData
      1 util
      1 vectorized
      1 VersionInfo
      1 wfile
      1 WhichOneof
      2 abspath
      2 ACK
      2 Adadelta
      2 AdamW
      2 adp
      2 argsort
      2 asnumpy
      2 ast
      2 autograd
      2 AutoModelForSequenceClassification
      2 AutoTokenizer
      2 AUTOTUNE
      2 BaseHTTPRequestHandler
      2 BinaryIO
      2 CifarPartitionedTestCase
      2 CifarRayClient
      2 classmethod
      2 configparser
      2 continous
      2 ConvTranspose
      2 CreateInstanceFailure
      2 DataCollatorWithPadding
      2 demominator
      2 deserialisation
      2 deserializer
      2 edgecolor
      2 EfficientNetB
      2 el
      2 eq
      2 FashionMnistClient
      2 fedadagrad
      2 fll
      2 FlowerClient
      2 FlwrClient
      2 Formatter
      2 FORMATTER
      2 fromarray
      2 frozenset
      2 fss
      2 functools
      2 getattr
      2 getitem
      2 getLogger
      2 groupby
      2 hostname
      2 HTTPHandler
      2 HTTPServer
      2 IgnoreHostKeyPolicy
      2 ImageNetClient
      2 IMDBClient
      2 ImportError
      2 INI
      2 InstanceIdNotFound
      2 iw
      2 jsons
      2 keepdim
      2 lfd
      2 lgd
      2 linestyle
      2 linewidth
      2 LogRecord
      2 LogServer
      2 LongTensor
      2 lss
      2 lstm
      2 MARKERSIZE
      2 matmul
      2 maxk
      2 memoize
      2 MetricsEntry
      2 mhat
      2 mobilenetv
      2 nll
      2 NoMatchingInstanceType
      2 NoPublicFacingPortFound
      2 NotImplementedError
      2 opacus
      2 paramiko
      2 paramseters
      2 ParseFromString
      2 PIL
      2 preds
      2 pretrained
      2 PrivacyEngine
      2 proba
      2 ps
      2 pytest
      2 pytorch
      2 PytorchMNISTClient
      2 qfedavg
      2 QFFEDAVG
      2 quantized
      2 randn
      2 readlines
      2 ReconnectResultsAndFailures
      2 rect
      2 rects
      2 reparametrize
      2 RequestHandler
      2 ResourceWarning
      2 RunInstancesResult
      2 SaveModelStrategy
      2 semver
      2 serializer
      2 setattr
      2 setFormatter
      2 ShakespeareLeafNet
      2 SoftmaxCrossEntropyLoss
      2 StartFailed
      2 StepLR
      2 TBWrapper
      2 TerminationFailure
      2 TestCriterion
      2 TimeoutError
      2 tmpdir
      2 tokenize
      2 traindir
      2 TypeVar
      2 UnFlatten
      2 UnknownServerMessage
      2 urls
      2 UserWarning
      2 valdir
      2 valset
      2 VectorizedDPKerasSGDOptimizer
      2 vhat
      2 VisionDataset
      2 xaxis
      2 xticklabels
      3 adam
      3 addHandler
      3 ArgumentTypeError
      3 asarray
      3 assertEqual
      3 BaseSetting
      3 BytesIO
      3 ConfigEntry
      3 crossentropy
      3 CustomHTTPHandler
      3 dataclasses
      3 datagen
      3 datetime
      3 DefaultStrategy
      3 dest
      3 endswith
      3 ExponentialDecay
      3 FailingCLient
      3 FedAdam
      3 FEDBN
      3 fedopt
      3 FedYogi
      3 ffl
      3 figsize
      3 FitResultsAndFailures
      3 FLOWERSERVICE
      3 FlowerServiceStub
      3 FormatStrFormatter
      3 FromString
      3 getCIFAR
      3 getenv
      3 GetParameters
      3 getsockname
      3 glorot
      3 gpus
      3 GraphDef
      3 INET
      3 initializers
      3 InstanceIds
      3 KerasClientWrapper
      3 keyfunc
      3 LitAutoEncoder
      3 LOGDIR
      3 LogitsSavedModelHead
      3 LogRegParams
      3 makedirs
      3 microbatches
      3 MNISTNet
      3 normpath
      3 numel
      3 OneofDescriptor
      3 partitioner
      3 preprocess
      3 protoc
      3 QffedAvg
      3 qs
      3 QuantizableBase
      3 RayClientProxy
      3 realpath
      3 ResNet
      3 REUSEADDR
      3 RuntimeError
      3 savefig
      3 SerializeToString
      3 ServicerContext
      3 setsockopt
      3 sgd
      3 SSHCredentials
      3 startswith
      3 StatusTimeout
      3 strftime
      3 SUBNET
      3 SuccessClient
      3 tearDown
      3 TemporaryDirectory
      3 TensorDataset
      3 TensorSpec
      3 tolist
      3 TorchVision
      3 uuid
      3 valloader
      3 xlabel
      3 xlim
      3 xticks
      3 Xy
      3 ylabel
      3 ylim
      3 yticklabels
      4 Accuracies
      4 ag
      4 argmax
      4 argv
      4 astype
      4 BatchNorm
      4 bbox
      4 casted
      4 CategoricalCrossentropy
      4 coef
      4 CompositeEvalMetric
      4 conn
      4 contextmanager
      4 CopyFrom
      4 CrossEntropy
      4 dataloader
      4 dataloaders
      4 del
      4 DescribeInstancesResult
      4 distro
      4 dl
      4 dp
      4 Enum
      4 EvaluateResultsAndFailures
      4 ExecInfo
      4 expanduser
      4 FedAvgAndroid
      4 filepath
      4 filterwarnings
      4 fs
      4 http
      4 ImageFolder
      4 InstanceMismatch
      4 ips
      4 isdir
      4 js
      4 KerasModelHead
      4 kld
      4 loc
      4 MNISTClient
      4 mse
      4 openml
      4 pre
      4 probs
      4 PROTO
      4 quantizable
      4 rcParams
      4 rmtree
      4 setUpClass
      4 SFTPAttributes
      4 sqrt
      4 SSHClient
      4 SubsetRandomSampler
      4 TBW
      4 tcp
      4 TestTfliteTransferConverter
      4 tokenizer
      4 tqdm
      4 urllib
      4 yticks
      5 atleast
      5 attr
      5 barwidth
      5 contextlib
      5 DockerAdapter
      5 DPCifarClient
      5 EnumValueDescriptor
      5 FedAdagrad
      5 formatter
      5 GETPARAMETERS
      5 hs
      5 LegendLoc
      5 metavar
      5 MissingHostKeyPolicy
      5 mkdtemp
      5 ModelCorrectnessTest
      5 NumPyClientWrapper
      5 perf
      5 protobuf
      5 ReLU
      5 SimpleNet
      5 sklearn
      5 tobytes
      5 yaxis
      6 arg
      6 ClientSettingNotFound
      6 const
      6 DATASET
      6 dpsgd
      6 env
      6 environ
      6 FastAndSlow
      6 func
      6 kwargs
      6 logfile
      6 MNIST
      6 MnistClient
      6 Namespace
      6 nd
      6 PARAMETERSRES
      6 PathLike
      6 QFedAvg
      6 rdp
      6 topk
      6 trainings
      6 tt
      6 unregister
      6 url
      7 assertModelAchievesAccuracy
      7 ClientFn
      7 cmd
      7 compat
      7 deserialized
      7 FedOpt
      7 HasField
      7 imagenet
      7 imgs
      7 importlib
      7 LOGFILE
      7 mkdir
      7 ndim
      7 PROPERTIESENTRY
      7 sftp
      7 shutil
      7 StopIteration
      7 TFLiteConverter
      7 TransferModel
      8 accuracies
      8 bn
      8 cls
      8 ctx
      8 dirname
      8 fedfs
      8 FlowerServiceServicer
      8 html
      8 KerasClient
      8 ModuleList
      8 ok
      8 regularizers
      8 rpc
      8 SavedModelBase
      8 servicer
      8 sess
      8 subnet
      8 tensorboard
      9 cen
      9 FedFSv
      9 GRPCBridgeClosed
      9 logdir
      9 pathlib
      9 stderr
      9 TFLiteTransferConverter
      9 ThreadPoolExecutor
      9 unpartitioned
      9 VisionClassificationClient
     10 boto
     10 cids
     10 Config
     10 contribs
     10 LogisticRegression
     10 matplotlib
     10 NDArrayIter
     10 qffl
     10 regularizer
     10 stdout
     11 abc
     11 AdapterInstance
     11 Dataset
     11 pred
     11 rng
     11 tokenized
     12 bs
     12 dirichlet
     12 eps
     12 frac
     12 fvalue
     12 gca
     12 GRPC
     12 ip
     12 repr
     12 resnet
     12 setLevel
     12 SoftmaxClassifierHead
     12 tempfile
     12 tflite
     12 ws
     13 assertRaises
     13 exc
     13 iter
     13 logvar
     13 tmp
     14 FaultTolerantFedAvg
     14 GRPCBridge
     14 logserver
     14 METRICSENTRY
     14 PROPERTIESINS
     14 PROPERTIESRES
     14 setUp
     15 EVALUATEINS
     15 EVALUATERES
     15 FITINS
     15 fontsize
     15 gpu
     15 MobileNetV
     15 oneof
     15 sys
     16 assertSignatureEqual
     16 cv
     16 durations
     16 io
     16 PartitionedDataset
     16 SimpleClientManager
     17 arange
     17 FITRES
     17 MaxPool
     17 TestCase
     17 ToTensor
     18 dataclass
     18 PARAMS
     20 CONFIG
     20 CrossEntropyLoss
     20 GeneratedProtocolMessageType
     20 mobilenet
     20 mxnet
     20 RegisterMessage
     20 serde
     20 tfltransfer
     21 CONFIGENTRY
     21 cuda
     22 nb
     23 elif
     24 CifarClient
     24 optim
     24 pb
     24 SGD
     24 sym
     25 cnn
     26 ArgumentParser
     26 ClientSetting
     26 GrpcClientProxy
     27 logits
     28 NumPyClient
     28 optimizers
     28 PropertiesIns
     29 acc
     29 MagicMock
     29 XYList
     30 isinstance
     30 plt
     30 PropertiesRes
     31 img
     31 initializer
     31 softmax
     32 lda
     32 timeit
     34 Conv
     36 ValueError
     37 BaseException
     37 CIFAR
     37 OrderedDict
     38 ec
     38 param
     39 ClientManager
     39 relu
     40 tfv
     41 fedavg
     41 ParametersRes
     42 conv
     43 abstractmethod
     43 mx
     47 cpp
     47 ds
     47 FieldDescriptor
     47 nda
     50 ceil
     50 oneofs
     51 FedAvg
     52 EvaluateIns
     53 trainset
     55 IID
     55 unittest
     57 tensorflow
     58 json
     59 ServerSetting
     60 mnist
     60 ServerMessage
     61 argparse
     61 FitIns
     63 testset
     64 fc
     65 torchvision
     67 params
     68 os
     73 enum
     74 DataLoader
     76 EvaluateRes
     79 XY
     82 bool
     82 cifar
     82 ClientMessage
     83 NUM
     86 dtype
     86 FitRes
     88 SERVERMESSAGE
     92 CLIENTMESSAGE
     93 dir
     94 trainloader
     96 msg
     97 lr
     99 grpc
    106 testloader
    109 ClientProxy
    109 iid
    113 cpu
    113 datasets
    114 utils
    116 numpy
    123 init
    128 FN
    132 rnd
    136 proto
    177 dataset
    179 keras
    195 nn
    196 cid
    217 args
    226 idx
    226 ndarray
    226 xy
    252 eval
    256 len
    286 flwr
    290 fn
    328 tf
    401 config
    583 str
    632 np
   1097 num
```
</details>

### CODE REVIEW

**Comment by sisco0** [comment]
It seems that some typing errors are showing up in the baselines.

**Review by danieljanes — APPROVED** [review]

**Comment by danieljanes** [comment]
@sisco0 really cool, love the approach you took here :)

@pedropgusmao any thoughts on the baselines typing error? https://github.com/adap/flower/runs/4684828079?check_suite_focus=true

**Comment by tanertopal** [comment]
@sisco0 fully agree with Daniel! Super cool approach! 🚀

**Comment by tanertopal** [comment]
Merged! Thank you @sisco0

**Pull request merged**
